# DBRepo Demo Notebook

## Environment

Set the REST API endpoint and your username + password in the `.env` file. This ensures it is not revealed in the code.

In [1]:
import dotenv
from pandas.core.interchange.dataframe_protocol import DataFrame
%load_ext dotenv
%dotenv

The code above loads the values from the `.env` file into this Jupyter Notebook. Alternatively you can set all parameters directly in the method:
 
```python
client = RestClient(endpoint='https://test.dbrepo.tuwien.ac.at', username='foo', password='bar')
```

## Global Variables & Imports

Set the database id for convenience.

In [2]:
from dbrepo.RestClient import RestClient

database_id = 37
client = RestClient()

## Tables

Load data from any table, uncomment where needed.

In [3]:
# test_result_chloride_ageing = client.get_table_data(database_id, 615)
# test_result_chloride = client.get_table_data(database_id, 614)
# test_result_carb_nat = client.get_table_data(database_id, 613)
# test_result_carb_acc = client.get_table_data(database_id, 612)
# source_mat_analysis = client.get_table_data(database_id, 611)
# source_mat = client.get_table_data(database_id, 610)
# pruefstelle = client.get_table_data(database_id, 609)
# mix_recipe = client.get_table_data(database_id, 607)
# mix = client.get_table_data(database_id, 606)
betonvariante = client.get_table_data(database_id, 604)
betonvariante

# optional: export table data as .csv
# betonvariante.to_csv('betonvariante.csv')

# optional: update table data from .csv
# client.import_table_data(database_id, 604, 'my_data.csv')

# optional: update table data from `pandas` DataFrame
# df = DataFrame()
# client.import_table_data(database_id, 604, df)

  id name
0  1    s
1  2    d
2  3    p
3  4    c

## Views

Load data from any view, uncomment where needed.

In [4]:
beton_acc = client.get_view_data(database_id, 70)
beton_acc

# optional: export view data as .csv
# beton_acc.to_csv('beton_acc.csv')

,mix,date_production,name,k_ac_mm_root_day,test_procedure,mean_depth_t0_mm
0,20230918-N01-XC2-D,2023-09-18,d,1.590000000000000000,KB-TVFA,0.750000000000000000
1,20230918-N03-XC1-S,2023-09-18,s,2.070000000000000000,KB-TVFA,0.250000000000000000
2,20230919-N03-XC1-D,2023-09-19,d,1.390000000000000000,KB-TVFA,0.200000000000000000
3,20230920-N03-XC2-D,2023-09-20,d,1.260000000000000000,KB-TVFA,0.300000000000000000
4,20230918-N04-XC1-S,2023-09-18,s,2.090000000000000000,KB-TVFA,0.300000000000000000
5,20230919-N06-XC1-S,2023-09-19,s,1.070000000000000000,KB-TVFA,0E-18
6,20230920-N06-XC2-D,2023-09-20,d,0.770000000000000000,KB-TVFA,0E-18

## Subsets

In [5]:
subset = client.create_subset(database_id, "SELECT m.mix, date_production, b.name, ta.k_ac_mm_root_day, ta.test_procedure, ta.mean_depth_t0_mm FROM mix m JOIN betonvariante b ON b.id = m.betonvariante_id JOIN test_result_carb_acc ta ON m.id = ta.mix_id")
subset

ResponseCodeError: Failed to create subset: response code: 200 is not 201 (CREATED): [{"mix":"20230918-N01-XC2-D","date_production":"2023-09-18","name":"d","k_ac_mm_root_day":"1.590000000000000000","test_procedure":"KB-TVFA","mean_depth_t0_mm":"0.750000000000000000"},{"mix":"20230918-N03-XC1-S","date_production":"2023-09-18","name":"s","k_ac_mm_root_day":"2.070000000000000000","test_procedure":"KB-TVFA","mean_depth_t0_mm":"0.250000000000000000"},{"mix":"20230919-N03-XC1-D","date_production":"2023-09-19","name":"d","k_ac_mm_root_day":"1.390000000000000000","test_procedure":"KB-TVFA","mean_depth_t0_mm":"0.200000000000000000"},{"mix":"20230920-N03-XC2-D","date_production":"2023-09-20","name":"d","k_ac_mm_root_day":"1.260000000000000000","test_procedure":"KB-TVFA","mean_depth_t0_mm":"0.300000000000000000"},{"mix":"20230918-N04-XC1-S","date_production":"2023-09-18","name":"s","k_ac_mm_root_day":"2.090000000000000000","test_procedure":"KB-TVFA","mean_depth_t0_mm":"0.300000000000000000"},{"mix":"20230919-N06-XC1-S","date_production":"2023-09-19","name":"s","k_ac_mm_root_day":"1.070000000000000000","test_procedure":"KB-TVFA","mean_depth_t0_mm":"0E-18"},{"mix":"20230920-N06-XC2-D","date_production":"2023-09-20","name":"d","k_ac_mm_root_day":"0.770000000000000000","test_procedure":"KB-TVFA","mean_depth_t0_mm":"0E-18"}]